# fly.toml app configuration file generated for teamsnap on 2023-10-31T18:49:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "teamsnap"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false
